version: '3.8'
services:
  kimai:
    image: kimai/kimai2:apache
    ports:
      - "8001:8001"
    environment:
      - ADMINMAIL=admin@empresa.com
      - ADMINPASS=senha_segura_123
      - DATABASE_URL=mysql://user:password@mysql:3306/kimai?serverVersion=8.0
      - TRUSTED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped

  kimai:
    image: kimai/kimai2:apache
    container_name: kimai
    ports:
      - "0.0.0.0:8001:8001"
    environment:
      - ADMINMAIL=admin@empresa.com
      - ADMINPASS=senha_segura_123
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai?charset=utf8mb4&serverVersion=8.3.0
      - TRUSTED_HOSTS=localhost,127.0.0.1
    volumes:
      - kimai-data:/opt/kimai/var/data  
      - ./var/export:/opt/kimai/var/export  # Adicione esta linha
      - ./var/plugins:/opt/kimai/var/plugins  # Adicione esta linha
      - ./local.yaml:/opt/kimai/config/local.yaml  # Adicione esta linha
      - ./public/images:/opt/kimai/public/images  # Mapeia apenas a pasta de imagens    restart: unless-stopped
    depends_on:
      - sqldb

volumes:
  kimai-mysql-data:
  kimai-data: